### ISSUE TITLE
Reaction Chamber crash

### ISSUE THREAD

**Issue by roboderpy** [pWn3d1337/Techguns2#12]
If reaction chamber is working and all players left the server, server crashes

```
java.lang.NullPointerException: Ticking block entity
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source)
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(Unknown Source)
	at java.lang.reflect.Field.get(Unknown Source)
	at techguns.tileentities.ReactionChamberTileEntMaster.needFluidUpdate(ReactionChamberTileEntMaster.java:709)
	at techguns.tileentities.ReactionChamberTileEntMaster.func_73660_a(ReactionChamberTileEntMaster.java:220)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by randomei** [comment]
I can confirm this bug.

**Comment by pWn3d1337** [comment]
Pre releases should have a fix to this:
https://github.com/pWn3d1337/Techguns2/releases

**Comment by a-c-engler** [comment]
Thanks, it works!
