### ISSUE TITLE
Intermittent render crash

### ISSUE THREAD

**Issue by LemADEC** [pWn3d1337/Techguns2#158]
As of 1.12.2-2.0.2.0_pre3.1, client crashes intermittently when loading/unlaoding chunks with a TechGuns grinder in it.
https://gist.github.com/LemADEC/5547dbf29e45b9a8d4d3f6e320c8e5d2
```
java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at techguns.client.render.tileentities.RenderGrinder.render(RenderGrinder.java:51)
	at techguns.client.render.tileentities.RenderGrinder.func_192841_a(RenderGrinder.java:24)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:155)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:130)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:705)
...
```

**Comment by ProsperCraft** [comment]
https://paste.dimdev.org/vomafocazu.mccrash

Same crash with techguns-1.12.2-2.0.2.0_pre3.1 as well.

**Comment by ProsperCraft** [comment]
Another client crash - please release

https://gist.github.com/ProsperCraft/55507dff4567aa7c5e5be353b125b4dd
