### ISSUE TITLE
Unknown item 'patchouli:guide_book'

### ISSUE THREAD

**Issue by Cube-8K** [pWn3d1337/Techguns2#193]
Everytime my server starts, it gives this error during it, but no crash, the mod seems to be working well, and doens't appear any guide book or something. Now I have this mod and IndustrialCraft 2 v2.8.195-ex112. It's running Magma 1.12.2

[22:33:34] [Server thread/ERROR] [FML]: Parsing error loading recipe techguns:techguns_manual_alt
com.google.gson.JsonSyntaxException: Unknown item 'patchouli:guide_book'
at net.minecraftforge.common.crafting.CraftingHelper.getItemStack(CraftingHelper.java:214) ~[CraftingHelper.class:45bb996]
at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$15(CraftingHelper.java:538) ~[CraftingHelper.class:45bb996]
at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:416) ~[CraftingHelper.class:45bb996]
at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:723) ~[CraftingHelper.class:45bb996]
at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) ~[CraftingHelper.class:45bb996]
at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:688) ~[CraftingHelper.class:45bb996]
at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_242]
at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:633) [CraftingHelper.class:45bb996]
at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:721) [Loader.class:45bb996]
at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:112) [FMLServerHandler.class:45bb996]
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:340) [FMLCommonHandler.class:45bb996]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:264) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:668) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
> [22:33:34] [Server thread/ERROR] [FML]: Parsing error loading recipe techguns:techguns_manual
com.google.gson.JsonSyntaxException: Unknown item 'patchouli:guide_book'
at net.minecraftforge.common.crafting.CraftingHelper.getItemStack(CraftingHelper.java:214) ~[CraftingHelper.class:45bb996]
at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$15(CraftingHelper.java:538) ~[CraftingHelper.class:45bb996]
at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:416) ~[CraftingHelper.class:45bb996]
at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:723) ~[CraftingHelper.class:45bb996]
at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) ~[CraftingHelper.class:45bb996]
at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:688) ~[CraftingHelper.class:45bb996]
at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_242]
at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:633) [CraftingHelper.class:45bb996]
at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:721) [Loader.class:45bb996]
at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:112) [FMLServerHandler.class:45bb996]
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:340) [FMLCommonHandler.class:45bb996]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:264) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:668) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

If u need the entire start up log, pls let me know, it's my first time using GitHub, and posting an issue XD

**Comment by Cube-8K** [comment]
If u need the entire start up log, let me know, it's my firt time using GitHub, and posting an issue at all XD

**Comment by Master-Henry2006** [comment]
Patchouli is a optional dependency for Techguns. This Error will be the result, if you haven't installed Patchouli. It would add a guide book for Techguns, if it has been installed. The Error isn't bad, it is only the notification, that patchouli isn't installed.

**Comment by Cube-8K** [comment]
I really didn't expect that could be a simple notification. Now with the guide book working, it will help a lot. Thanks 4 the help. That thing showing up everytime the server starts is very annoying :v
