### ISSUE TITLE
Client crash when using blacklisted item from item blacklist mod

### ISSUE THREAD

**Issue by ChristianTAcosta** [pWn3d1337/Techguns2#198]
Techguns causes minecraft client to crash when a black listed item is equipped in the Techguns inventory.  

`java.lang.ClassCastException: net.doubledoordev.itemblacklist.util.ItemBlacklisted cannot be cast to techguns.api.tginventory.ITGSpecialSlot at techguns.items.armors.GenericArmor.getBonusForSlot(GenericArmor.java:341) at techguns.items.armors.GenericArmor.getArmorBonusForPlayer(GenericArmor.java:331) at techguns.events.TGTickHandler.onPlayerTick(TGTickHandler.java:301) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_480_TGTickHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic) at`

**Comment by pWn3d1337** [comment]
Why would non TG item even be equipped there? The slot is supposed to only allow items implementing ITGSpecialSlot

**Comment by ChristianTAcosta** [comment]
> Why would non TG item even be equipped there? The slot is supposed to only allow items implementing ITGSpecialSlot

The item blacklist mod works by putting a blacklisted item inside an item container. this basically locks the item and prevents the user from interacting with the original item. The black list mod allows server admins to ban items in certain dimensions.

**Comment by pWn3d1337** [comment]
Techguns expects an item to be ITGSpecialSlot, this could potentially cause problems at multiple locations in the code. I don't like adding a type check for something that is not even supposed to happen.
