### ISSUE TITLE
Epic fight + Tech guns

### ISSUE THREAD

**Issue by Bruno-Calasans** [pWn3d1337/Techguns2#269]
I got this crash when i tried to load a new world. Vanilla fix said this come from epic fight and tech guns:
[crash-2021-08-26_19.23.44-client.txt](https://github.com/pWn3d1337/Techguns2/files/7063059/crash-2021-08-26_19.23.44-client.txt)

Then i created a new one and this happening:
![image](https://user-images.githubusercontent.com/83395524/131044770-65e04a42-c52c-4dca-8bb7-24f3528c4b01.png)

**Comment by dazadazu** [comment]
Mostly Epicfightmod, crashes a lot it seems.

**Comment by ubergarm** [comment]
Hrmm just found this ticket after receiving a similar error using `EpicFightMod-1.12.2-2.2.7.jar` + `techguns-1.12.2-2.0.2.0_pre3.2.jar` in Minecraft 1.12.2... 

I tried without optifine and still got the crash, and disabling Epic Fight stopped the crashing.

I opened a ticket over at the `Epic Fight` github with full crash report as well.

Here is the crash stack trace snippet here just in case it helps or confirms the issue for anyone else.
```
Description: Rendering entity in world

 java.lang.NullPointerException: Rendering entity in world
     at techguns.client.render.ItemRenderHack.shouldRenderItem(ItemRenderHack.java:124)
     at techguns.client.render.ItemRenderHack.renderItem(ItemRenderHack.java:54)
     at net.minecraft.client.renderer.RenderItem.func_181564_a(RenderItem.java:384)
     at codechicken.lib.render.item.CCRenderItem.func_181564_a(CCRenderItem.java:293)
     at maninthehouse.epicfight.client.renderer.item.RenderItemBase.renderItemInHand(RenderItemBase.java:42)
     at maninthehouse.epicfight.client.renderer.layer.HeldItemLayer.renderLayer(HeldItemLayer.java:44)
     at maninthehouse.epicfight.client.renderer.entity.ArmatureRenderer.renderLayer(ArmatureRenderer.java:81)
     at maninthehouse.epicfight.client.renderer.entity.ArmatureRenderer.render(ArmatureRenderer.java:46)
     at maninthehouse.epicfight.client.events.engine.RenderEngine.renderEntityArmatureModel(RenderEngine.java:202)
     at maninthehouse.epicfight.client.events.engine.RenderEngine$Events.renderLivingEvent(RenderEngine.java:307)
     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_270_Events_renderLivingEvent_Pre.invoke(.dynamic)
     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
     at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
     at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
     at sun.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at net.optifine.reflect.Reflector.call(Reflector.java:976)
     at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1251)
     at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1237)
     at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:114)
     at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:50)
```

Cheers!

**Comment by ubergarm** [comment]
Quick update: I just tested with the slightly older version of Tech Guns `techguns-1.12.2-2.0.2.0_pre3.1.jar` and the crash seems to go away!

Gonna just use old version for now until maybe someone figures it out on either side.

Cheers and thanks!
