### ISSUE TITLE
Crash when I use JEI to search up Techguns addons, crash blames Techguns, Lucraft, and JEI

### ISSUE THREAD

**Issue by Velocihater** [pWn3d1337/Techguns2#60]
Time: 2018-09-02 12:41:21 CDT
Description: Rendering ingredient

java.lang.NullPointerException
    at lucraft.mods.lucraftcore.advancedcombat.AdvancedCombatClientEventHandler.onSetupModel(AdvancedCombatClientEventHandler.java:108)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1554_AdvancedCombatClientEventHandler_onSetupModel_SetRotationAngels.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at lucraft.mods.lucraftcore.core.LCClientHooks.renderBipedPre(LCClientHooks.java:26)
    at net.minecraft.client.model.ModelBiped.render(SourceFile:79)
    at techguns.client.render.item.RenderArmorItem.renderItem(RenderArmorItem.java:92)
    at techguns.client.render.ItemRenderHack.renderItem(ItemRenderHack.java:73)
    at net.minecraft.client.renderer.RenderItem.renderModel(RenderItem.java:134)
    at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:62)
    at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:31)
    at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:162)
    at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:94)
    at mezz.jei.gui.overlay.IngredientGridAll.draw(IngredientGridAll.java:89)
    at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:205)
    at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:51)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2578_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.client.gui.GuiScreen.drawDefaultBackground(GuiScreen.java:575)
    at net.minecraft.client.gui.inventory.GuiInventory.drawScreen(SourceFile:66)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
    at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.optifine.reflect.Reflector.callVoid(Reflector.java:654)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1456)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1118)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Ingredient being rendered --
  Ingredient Mod: Techguns
  Ingredient Info: 1xitem.steam_helmet@0 techguns:steam_helmet nbt:{power:0}

-- Screen render details --
  Screen name: net.minecraft.client.gui.inventory.GuiInventory
  Mouse location: Scaled: (573, 442). Absolute: (1146, 172)
  Screen size: Scaled: (960, 529). Absolute: (1920, 1057). Scale factor of 2

-- Affected level --
  Level name: MpServer
  All players: 1 total; [GCEntityClientPlayerMP['Velocihater'/451, l='MpServer', x=180.66, y=64.00, z=-137.53]]
  Chunk stats: MultiplayerChunkCache: 289, 289
  Level seed: 0
  Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (220,64,-128), Chunk: (at 12,4,0 in 13,-8; contains blocks 208,0,-128 to 223,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Level time: 1166577 game time, 787903 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 118 total; [EntityLaserCreeper['Laser Creeper'/258, l='MpServer', x=180.50, y=63.00, z=-241.50], MoCEntityRoach['Roach'/267, l='MpServer', x=179.18, y=70.00, z=-196.67], EntityDodo['Dodo'/268, l='MpServer', x=188.00, y=74.00, z=-194.54], EntityDodo['Dodo'/287, l='MpServer', x=191.50, y=78.00, z=-176.16], EntityPhyg['Phyg'/289, l='MpServer', x=180.73, y=61.00, z=-136.50], MoCEntityHorse['WildHorse'/290, l='MpServer', x=188.93, y=60.00, z=-136.95], EntityChameleon['Chameleon'/296, l='MpServer', x=207.50, y=79.00, z=-181.50], EntityDodo['Dodo'/298, l='MpServer', x=203.50, y=82.00, z=-161.50], EntityLostMiner['Ore Miner'/299, l='MpServer', x=194.34, y=44.00, z=-112.45], EntityLostMiner['Stone Miner'/300, l='MpServer', x=192.48, y=44.00, z=-113.99], EntityDodo['Dodo'/301, l='MpServer', x=199.50, y=85.00, z=-117.50], EntityBabySpider['Baby Spider'/312, l='MpServer', x=213.50, y=86.00, z=-119.68], EntityMotherSpider['Mother Spider'/313, l='MpServer', x=213.50, y=87.00, z=-121.50], EntityBabySpider['Baby Spider'/314, l='MpServer', x=213.50, y=87.70, z=-121.60], EntityItem['item.item.string'/315, l='MpServer', x=215.88, y=88.00, z=-125.43], EntityGrue['Grue'/316, l='MpServer', x=219.56, y=62.51, z=-113.30], EntityChameleon['Chameleon'/317, l='MpServer', x=210.57, y=75.00, z=-107.75], EntityChupacabra['Chupacabra'/318, l='MpServer', x=210.50, y=48.00, z=-95.50], EntityChupacabra['Chupacabra'/337, l='MpServer', x=225.78, y=36.00, z=-238.48], EntityFestiveCreeper['Festive Creeper'/338, l='MpServer', x=229.50, y=31.00, z=-216.50], EntityPufferFish['Pufferfish'/339, l='MpServer', x=220.13, y=62.04, z=-216.85], EntitySockeyeSalmon['Sockeye Salmon'/340, l='MpServer', x=237.89, y=62.14, z=-205.82], EntityChupacabra['Chupacabra'/341, l='MpServer', x=230.53, y=25.00, z=-199.92], EntityChupacabra['Chupacabra'/342, l='MpServer', x=231.52, y=23.00, z=-204.81], EntityChupacabra['Chupacabra'/343, l='MpServer', x=233.54, y=32.00, z=-204.32], EntityChupacabra['Chupacabra'/344, l='MpServer', x=234.27, y=32.00, z=-201.30], EntityPufferFish['Pufferfish'/345, l='MpServer', x=235.15, y=62.02, z=-206.80], EntityRocketCreeper['Rocket Creeper'/346, l='MpServer', x=234.50, y=63.00, z=-205.50], MoCEntitySnail['Snail'/347, l='MpServer', x=234.61, y=74.00, z=-179.12], MoCEntitySnail['Snail'/348, l='MpServer', x=232.50, y=66.00, z=-167.57], MoCEntitySnail['Snail'/349, l='MpServer', x=225.19, y=78.00, z=-171.63], MoCEntityCrab['Crab'/350, l='MpServer', x=231.79, y=67.00, z=-153.53], MoCEntityDragonfly['DragonFly'/351, l='MpServer', x=231.50, y=67.00, z=-145.43], EntityZooKeeper['Zoo Keeper'/352, l='MpServer', x=238.24, y=82.00, z=-141.48], MoCEntityBee['Bee'/353, l='MpServer', x=237.52, y=64.00, z=-117.66], EntityFestiveCreeper['Festive Creeper'/354, l='MpServer', x=239.50, y=11.00, z=-99.50], EntityChupacabra['Chupacabra'/355, l='MpServer', x=238.95, y=41.00, z=-80.49], EntityChupacabra['Chupacabra'/356, l='MpServer', x=233.50, y=23.00, z=-78.50], EntityTreasureSlime['Treasure Slime'/357, l='MpServer', x=228.74, y=17.02, z=-69.61], EntityChupacabra['Chupacabra'/358, l='MpServer', x=236.50, y=43.00, z=-66.50], EntityLostMiner['Gem Miner'/359, l='MpServer', x=231.69, y=23.00, z=-57.56], MoCEntityCricket['Cricket'/360, l='MpServer', x=233.46, y=64.00, z=-65.48], EntityChupacabra['Chupacabra'/377, l='MpServer', x=246.28, y=16.00, z=-212.53], EntityEnchantedBook['Bewitched Tome'/378, l='MpServer', x=243.50, y=21.00, z=-215.50], EntityFish['entity.BlueFish.name'/380, l='MpServer', x=250.00, y=62.09, z=-200.65], EntitySockeyeSalmon['Sockeye Salmon'/381, l='MpServer', x=251.30, y=62.09, z=-194.83], EntityClownFish['Clownfish'/382, l='MpServer', x=253.73, y=62.03, z=-189.15], EntityChupacabra['Chupacabra'/383, l='MpServer', x=246.80, y=39.00, z=-173.50], EntityChupacabra['Chupacabra'/384, l='MpServer', x=245.84, y=40.00, z=-168.59], EntityChupacabra['Chupacabra'/385, l='MpServer', x=246.50, y=42.00, z=-166.20], EntityChupacabra['Chupacabra'/386, l='MpServer', x=243.63, y=40.00, z=-170.24], MoCEntityCrab['Crab'/387, l='MpServer', x=241.27, y=63.00, z=-172.03], EntityChupacabra['Chupacabra'/388, l='MpServer', x=240.25, y=47.00, z=-81.32], EntityClownFish['Clownfish'/394, l='MpServer', x=260.16, y=62.00, z=-193.15], EntityClownFish['Clownfish'/395, l='MpServer', x=258.15, y=65.81, z=-198.86], EntityChupacabra['Chupacabra'/396, l='MpServer', x=256.99, y=42.00, z=-169.19], EntitySilex['Silex'/400, l='MpServer', x=269.54, y=62.16, z=-37.63], EntitySilex['Silex'/401, l='MpServer', x=273.45, y=62.20, z=-34.06], EntityLatchedRenderer['unknown'/657, l='MpServer', x=180.66, y=64.00, z=-137.53], MoCEntityBee['Bee'/153, l='MpServer', x=110.51, y=106.00, z=-207.51], MoCEntityBee['Bee'/154, l='MpServer', x=114.99, y=106.00, z=-209.00], MoCEntityButterfly['ButterFly'/155, l='MpServer', x=111.50, y=106.00, z=-207.87], MoCEntityCricket['Cricket'/156, l='MpServer', x=111.50, y=106.00, z=-205.50], EntitySilex['Silex'/412, l='MpServer', x=281.40, y=61.83, z=-27.76], EntityEpion['Epion'/157, l='MpServer', x=101.20, y=127.65, z=-202.53], EntityChupacabra['Chupacabra'/158, l='MpServer', x=104.86, y=47.00, z=-190.72], MoCEntityFly['Fly'/159, l='MpServer', x=108.54, y=61.53, z=-139.21], EntityChupacabra['Chupacabra'/160, l='MpServer', x=103.58, y=14.00, z=-121.40], EntityBabySpider['Baby Spider'/161, l='MpServer', x=103.50, y=16.00, z=-114.50], EntitySpectre['Spectre'/673, l='MpServer', x=112.50, y=20.00, z=-105.50], EntityBabySpider['Baby Spider'/162, l='MpServer', x=102.35, y=19.00, z=-107.35], EntityDarkling['Darkling'/674, l='MpServer', x=133.50, y=20.00, z=-197.50], MoCEntityAngler['Angler'/165, l='MpServer', x=106.50, y=72.00, z=-96.50], EntityChupacabra['Chupacabra'/166, l='MpServer', x=109.46, y=44.00, z=-95.26], EntityGrue['Grue'/678, l='MpServer', x=121.44, y=22.00, z=-167.44], MoCEntityCod['Cod'/167, l='MpServer', x=107.50, y=75.00, z=-81.50], EntityDarkling['Azure Darkling'/679, l='MpServer', x=122.50, y=21.00, z=-166.50], MoCEntityHippoTang['HippoTang'/168, l='MpServer', x=108.50, y=75.00, z=-79.50], EntitySilex['Silex'/428, l='MpServer', x=291.37, y=61.86, z=-30.76], EntityChupacabra['Chupacabra'/187, l='MpServer', x=123.59, y=21.00, z=-162.71], EntityChupacabra['Chupacabra'/188, l='MpServer', x=121.94, y=22.00, z=-170.47], EntityChupacabra['Chupacabra'/189, l='MpServer', x=130.22, y=25.00, z=-174.50], MoCEntityFirefly['Firefly'/191, l='MpServer', x=124.48, y=74.00, z=-124.95], MoCEntityHippoTang['HippoTang'/192, l='MpServer', x=116.50, y=11.00, z=-104.50], EntityWraamon['Wraamon'/193, l='MpServer', x=127.49, y=28.00, z=-104.51], EntityGrue['Grue'/194, l='MpServer', x=120.56, y=19.00, z=-97.50], EntitySkeletonWarrior['Skeleton Warrior'/196, l='MpServer', x=126.50, y=78.00, z=-107.50], EntityEnchantedBook['Bewitched Tome'/197, l='MpServer', x=124.50, y=19.00, z=-87.50], GCEntityClientPlayerMP['Velocihater'/451, l='MpServer', x=180.66, y=64.00, z=-137.53], EntityChupacabra['Chupacabra'/198, l='MpServer', x=115.92, y=28.00, z=-74.35], EntityLatchedRenderer['unknown'/455, l='MpServer', x=8.50, y=65.00, z=8.50], EntityChupacabra['Verdant Chupacabra'/199, l='MpServer', x=121.43, y=23.00, z=-75.43], EntityChupacabra['Chupacabra'/200, l='MpServer', x=123.50, y=23.00, z=-74.50], EntityChupacabra['Chupacabra'/201, l='MpServer', x=118.46, y=26.17, z=-75.68], EntitySupportCreeper['Support Creeper'/717, l='MpServer', x=240.50, y=69.00, z=-128.50], EntityChupacabra['Chupacabra'/210, l='MpServer', x=131.47, y=22.00, z=-212.64], EntityChupacabra['Chupacabra'/211, l='MpServer', x=141.48, y=11.03, z=-198.52], EntityChupacabra['Chupacabra'/212, l='MpServer', x=135.86, y=21.00, z=-201.59], EntityDarkling['Darkling'/213, l='MpServer', x=142.50, y=18.00, z=-195.50], EntityHauntedTool['Haunted Tool'/469, l='MpServer', x=229.50, y=18.00, z=-75.50], EntityAnimalTrader['Animal Trader'/214, l='MpServer', x=140.51, y=80.00, z=-204.25], EntityDarkling['Azure Darkling'/215, l='MpServer', x=135.48, y=54.00, z=-164.52], EntityPinky['Scarlet Pinky'/216, l='MpServer', x=142.69, y=79.00, z=-174.29], EntityChupacabra['Chupacabra'/217, l='MpServer', x=128.33, y=24.00, z=-159.54], EntitySkeletonWarrior['Skeleton Warrior'/218, l='MpServer', x=131.50, y=36.00, z=-103.50], EntityChupacabra['Chupacabra'/227, l='MpServer', x=161.39, y=19.00, z=-243.00], EntityChupacabra['Chupacabra'/228, l='MpServer', x=155.72, y=51.00, z=-186.84], EntityChupacabra['Chupacabra'/229, l='MpServer', x=145.92, y=48.00, z=-188.19], EntityChameleon['Chameleon'/230, l='MpServer', x=154.50, y=69.00, z=-189.50], ZombieFarmer['Zombie Farmer'/231, l='MpServer', x=150.81, y=65.00, z=-162.47], EntityLostMiner['Stone Miner'/232, l='MpServer', x=145.70, y=49.00, z=-143.30], MoCEntityHippoTang['HippoTang'/233, l='MpServer', x=154.50, y=72.00, z=-101.50], EntityHauntedTool['Haunted Tool'/246, l='MpServer', x=166.55, y=67.00, z=-197.89], EntityChupacabra['Chupacabra'/247, l='MpServer', x=163.49, y=56.00, z=-184.65], MoCEntityCod['Cod'/251, l='MpServer', x=164.30, y=62.00, z=-111.70], MoCEntityMaggot['Maggot'/252, l='MpServer', x=167.84, y=79.00, z=-89.00], MoCEntityMaggot['Maggot'/253, l='MpServer', x=173.42, y=68.00, z=-90.81], EntityLatchedRenderer['unknown'/510, l='MpServer', x=180.66, y=64.00, z=-137.53]]
  Retry entities: 2 total; [EntityLatchedRenderer['unknown'/455, l='MpServer', x=8.50, y=65.00, z=8.50], EntityLatchedRenderer['unknown'/510, l='MpServer', x=180.66, y=64.00, z=-137.53]]
  Server brand: fml,forge
  Server type: Integrated singleplayer server

**Comment by Velocihater** [comment]
Also am using 2.0.1.2 pre 2

**Comment by pWn3d1337** [comment]
Looks like an incompatibility between lucraft and techguns. The crash is caused by lucraft while trying to render a techguns steam armor helmet.

**Comment by boosterdev** [comment]
somehow this also happends with other mods not sure wich ones though, and not crashing but rendering all guns as "image not found" in JEI only, ingame seems to be fine.

**Comment by pWn3d1337** [comment]
Guns don't render in inventory if you have a mod with conflicting ASM. (I know of eleccore causing such problems because it replaces some render methods).

**Comment by boosterdev** [comment]
removing that seems to solve the problem :+1:
