### ISSUE TITLE
[Compatibility] Latest Sponge(1.12.2-2768-7.1.4)

### ISSUE THREAD

**Issue by Fishkaras** [pWn3d1337/Techguns2#92]
Crash report(Full: https://pastebin.com/LcnM0MYE):
	net.minecraftforge.fml.common.MissingModsException: Mod techguns (Techguns) requires [forge@[14.23.5.2807,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

I know that Techguns since 1.12.2-2.0.1.2_pre3 requires latest forge (2807), recommended (2768) crashes on start.

Unfortunately, the latest version of the Sponge uses a stable version of the Forge(https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2).

A Sponge is a very important modding platform without which _stable_and_working_ chat, economy, land claims, fine tuning of rights and much more are impossible.

There is no tools to create a well-developed server on bare Forge.

So I just want to ask to add a compatibility layer for a stable Sponge(and Forge) version if possible. 

In parallel, I will ask the developers of Sponge to help for their part.

Thank you for your cooperation!

**Comment by Fishkaras** [comment]
We have just tested new Forge (2808) version with old Sponge (2768) and new Techguns and there is no compatibility issues at this moment. I'm sorry to trouble you.

**Comment by pWn3d1337** [comment]
Forge is usually compatible with mods built for older builds.
